import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Tag from "@/components/Tag";
import List from "@/components/List";
import { useEffect, useState } from "react";
import axios from "axios";
import Item from "@/components/Item";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [items, setItems] = useState([]);
  const getData = async () => {
    try {
      const data = await axios.get("http://localhost:7000/api/v1/item");
      setItems(data.data.items);
      console.log(data.data.items[0]);
    } catch (error) {}
  };
  useEffect(() => {
    getData();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen pb-5">
        <Navbar />
        {/* <List href="/SeeMore/hot-sales" link="/" title="Hot Sales"  />
        <List href="/SeeMore" link="/" title="Iphones" /> */}
        <div className="flex w-screen items-center justify-center p-4">
          <div className=" grid w-full max-w-5xl grid-cols-1 place-items-center gap-8 sm:grid-cols-3 md:grid-cols-4 md:gap-4">
            {items.map(
              (
                item: {
                  title: string;
                  compony: string;
                  status: string;
                  prise: number;
                  hot: boolean;
                  images: {
                    public_id: string;
                    url: string;
                  }[];
                },
                index
              ) => {
                return (
                  <Item
                    key={index}
                    item={{
                      title: item?.title,
                      compony: item?.compony,
                      status: item?.status,
                      prise: item?.prise,
                      hot: item?.hot,
                      images: item?.images,
                    }}
                  />
                );
              }
            )}
          </div>
        </div>
      </main>
    </>
  );
}

const Navbar = () => {
  return (
    <div className="flex w-screen items-center justify-center">
      <nav className="w-[90%] max-w-5xl p-4">
        <Image
          className="aspect-square"
          src="/next.svg"
          alt="Next.js Logo"
          width={80}
          height={20}
          priority
        />
      </nav>
    </div>
  );
};
